---
spring:
  config.activate.on-profile: default
cds:
  datasource:
    #auto-config.enabled: false
    url: "jdbc:sqlite:/home/user/projects/products-service/sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never
    hikari:
      maximum-pool-size: 1